import request from 'supertest';
import { createApp } from '@/app';
import { prisma } from '@/lib/prisma';
import { createUser, createMedicationPlan, authHeader } from './helpers/factories';

/**
 * Scoping shape under test: **nested relation**.
 *
 * `medicationRepository.findWithPlan` and `listByUser` do not filter on a
 * column of the row they return — they filter through a relation,
 * `where: { carePlan: { userId } }`. A mock cannot tell a correct nested filter
 * from a missing one, because the mock is what the filter would have run
 * against. Here the filter runs against real rows belonging to two real users.
 */

const app = createApp();

const isoDate = (offsetDays: number) => {
  const d = new Date();
  d.setDate(d.getDate() + offsetDays);
  return d.toISOString().slice(0, 10);
};

describe('medications — nested relation scoping', () => {
  it('creates a plan, its medication and its dose schedule in one transaction', async () => {
    const user = await createUser();

    const res = await request(app)
      .post('/api/v1/medications')
      .set(...authHeader(user))
      .send({
        name: 'Paracetamol',
        dosage: '500mg',
        frequency: 'TWICE_DAILY',
        startDate: isoDate(1),
        durationDays: 7,
        customTimes: ['08:00', '20:00'],
      });

    expect(res.status).toBe(201);
    expect(res.body.success).toBe(true);

    // The rows are really there — this is the assertion a mocked suite cannot make.
    const plans = await prisma.carePlan.findMany({ where: { userId: user.id } });
    expect(plans).toHaveLength(1);
    expect(plans[0].type).toBe('MEDICATION');

    const medication = await prisma.medication.findUnique({
      where: { carePlanId: plans[0].id },
    });
    expect(medication?.name).toBe('Paracetamol');

    // 7 days x twice daily, generated by the real scheduler and really inserted.
    const events = await prisma.careEvent.count({
      where: { carePlanId: plans[0].id },
    });
    expect(events).toBe(14);
  });

  it('lists only the caller’s own medications', async () => {
    const alice = await createUser();
    const bob = await createUser();

    await createMedicationPlan(alice.id, 'Amoxicillin');
    await createMedicationPlan(bob.id, 'Metformin');

    const aliceRes = await request(app)
      .get('/api/v1/medications')
      .set(...authHeader(alice));

    expect(aliceRes.status).toBe(200);
    const names = JSON.stringify(aliceRes.body.data);
    expect(names).toContain('Amoxicillin');
    expect(names).not.toContain('Metformin');
  });

  it('does not expose another user’s plan by id', async () => {
    const alice = await createUser();
    const bob = await createUser();

    const { carePlanId } = await createMedicationPlan(alice.id, 'Lisinopril');

    // Bob knows the id and asks for it directly. The nested scope is the only
    // thing standing between him and Alice's medication record.
    const res = await request(app)
      .get(`/api/v1/medications/${carePlanId}`)
      .set(...authHeader(bob));

    expect(res.status).toBe(404);
    expect(JSON.stringify(res.body)).not.toContain('Lisinopril');

    // And the row was not touched — a 404 must not mean "deleted".
    const stillThere = await prisma.carePlan.findUnique({ where: { id: carePlanId } });
    expect(stillThere).not.toBeNull();
  });

  it('leaves no rows behind between tests', async () => {
    // Proves the truncation in db-lifecycle actually runs: the three tests
    // above created users and plans, and this one starts from nothing.
    expect(await prisma.user.count()).toBe(0);
    expect(await prisma.carePlan.count()).toBe(0);
    expect(await prisma.careEvent.count()).toBe(0);
  });
});
