import { createReadStream, createWriteStream } from 'fs';
import { mkdir, stat, unlink, readdir } from 'fs/promises';
import { randomBytes } from 'crypto';
import path from 'path';

import { env } from '@/config/env';
import { createLogger } from '@/lib/logger';

const log = createLogger('reports-storage');

/**
 * Where a rendered summary lives between being generated and being fetched.
 *
 * This is the part of the async design that has to be handled carefully: for
 * as long as a file exists, one Person's whole health record is sitting
 * outside the tables that own it and outside the access checks that guard
 * them. Three things keep that bounded, and all three are enforced here rather
 * than left to callers:
 *
 *   * the name carries no meaning — no personId, no name, no period, so the
 *     directory listing discloses nothing even to someone who can read it
 *   * the file is written 0600 into a 0700 directory
 *   * every file has an expiry, and the sweep deletes it
 *
 * Nothing here authorises anything. Deciding *who* may fetch a document is the
 * service's job and happens against the database on every download; a key is
 * not a capability and must never be treated as one.
 */

/** An opaque name. 32 hex characters of randomness, and no information. */
export const newStorageKey = (): string => `${randomBytes(16).toString('hex')}.pdf`;

/**
 * Resolve a key to a path inside the storage directory.
 *
 * Keys are generated by this module and never supplied by a client, so this
 * cannot normally be reached with anything hostile. It is checked anyway: the
 * one thing a path bug in this file could do is serve or delete a file
 * somewhere else on the machine, and that is worth a strict-equality check.
 */
const resolvePath = (key: string): string => {
  const dir = path.resolve(env.REPORT_STORAGE_DIR);
  const full = path.resolve(dir, key);

  if (path.dirname(full) !== dir) {
    throw new Error('Refusing a report storage key that escapes the directory');
  }
  return full;
};

const ensureDir = async (): Promise<string> => {
  const dir = path.resolve(env.REPORT_STORAGE_DIR);
  await mkdir(dir, { recursive: true, mode: 0o700 });
  return dir;
};

/** A write stream for a new document. The caller pipes PDFKit into it. */
export const openWriteStream = async (key: string) => {
  await ensureDir();
  return createWriteStream(resolvePath(key), { mode: 0o600 });
};

/** Size in bytes, or null when the file is gone. */
export const fileSize = async (key: string): Promise<number | null> => {
  try {
    const info = await stat(resolvePath(key));
    return info.isFile() ? info.size : null;
  } catch {
    return null;
  }
};

export const openReadStream = (key: string) => createReadStream(resolvePath(key));

/**
 * Delete a document. Missing is success.
 *
 * The sweep and the download path can both reach this for the same file, and a
 * restart can remove the directory from under both. "Already gone" is the
 * outcome either wanted.
 */
export const deleteFile = async (key: string): Promise<void> => {
  try {
    await unlink(resolvePath(key));
  } catch (err: any) {
    if (err?.code !== 'ENOENT') {
      log.warn('Could not delete a report file', { error: err?.message });
    }
  }
};

/**
 * Files on disk that no row points at.
 *
 * These arise from a crash between writing the file and committing the row.
 * The sweep removes them: an orphan is a health record with nothing tracking
 * its expiry, which is the one state this design must not leave lying around.
 */
export const orphanedFiles = async (knownKeys: Set<string>): Promise<string[]> => {
  try {
    const names = await readdir(path.resolve(env.REPORT_STORAGE_DIR));
    return names.filter((name) => name.endsWith('.pdf') && !knownKeys.has(name));
  } catch (err: any) {
    if (err?.code === 'ENOENT') return [];
    throw err;
  }
};
